### ISSUE TITLE
no line numbers found

### ISSUE THREAD

**Issue by muralikodali** [Kilian/fromscratch#111]
I have installed appimage . I found **no line numbers** to use the feature "**go to line numbe**r" with shortcut Ctrl+g.
is this feature missing or is it an appimage problem ?

**Comment by Kilian** [comment]
Can you share a screenshot?

**Comment by muralikodali** [comment]
screenshot attached

![20200824T1834-screenshot](https://user-images.githubusercontent.com/11482766/91048076-bce67b80-e638-11ea-9dd3-1979ee953a7f.png)

**Comment by Kilian** [comment]
I get what you mean now. FromScratch doesn't show line numbers. But with ctrl+g you can still go to e.g. the 10th line.

**Comment by muralikodali** [comment]
thanks for the reply.

it is not easy to go to a line number  without counting lines . we can't count line numbers if the count goes up. I am expecting line numbers, as we see on the left side of window in vim and emacs . with visible line numbers,, navigation will become easier.
