### ISSUE TITLE
Feature Request: Shift+Tab to remove tab

### ISSUE THREAD

**Issue by ammmze** [Kilian/fromscratch#12]
Can we get support for `shift+tab`? This should remove the preceding tab character or a tab-width worth of spaces.

**Comment by Kilian** [comment]
<kbd>shift-tab</kbd> currently gets rid of the entire indentation. What is the reason you want a single tab removal?

**Comment by ammmze** [comment]
Interesting... For me it wasn't doing anything. I think im good with
removing the entire indentation. So maybe this should be bug report
instead. I'll have to try again when im at my computer.

**Comment by Kilian** [comment]
If it doesn't work, please let me know which OS you use.

**Comment by ammmze** [comment]
Looks like when first bringing it up it has some issues, but then starts working after tabbing in.

i'm running on OS X 10.11.3

See the [screencast](https://monosnap.com/file/meGSdNrZBXni3L3kmtLqamXTR9E6NY) I took of it...hopefully it helps.

**Comment by Kilian** [comment]
The default behaviour was a but under-specified (indent to 4 spaces when auto-indenting, shift tab only works If you use real tabs)

I now implemented the preferred behaviour: it uses tabs for indenting, supports pressing tab to indent 1 tab and supports pressing shift-tab to indent -1 tab. Should be in the next release!
