### ISSUE TITLE
Won't start on file windowstate corrupted

### ISSUE THREAD

**Issue by dhiller** [Kilian/fromscratch#14]
I received a strange error message when starting FromScratch today, from the stacktrace i could guess that it must have sth to do with saved state. 

Found out that file 'windowstate' in user data directory (~/.fromscratch in my case) was empty. Deleted the file, then application started up again.

OS is Linux Mint 17.3, used 64 bit version.

**Comment by Kilian** [comment]
can replicate, fix incoming!

**Comment by Kilian** [comment]
Fixed in the repository. I'll make a new release with this in soon.
