### ISSUE TITLE
Bug with long text

### ISSUE THREAD

**Issue by mattiabaldinazzo** [Kilian/fromscratch#148]
I'm having a bug with mac os M1 version.
I have copied and pasted a really long text (the entire html code of a web page) and now I have the following problem. If I try to select it all with Cmd + A or with the cursor the program crashes (keep loading). There is no menu item to reset the notes and I cannot find the saved file to delete it manually.
How to behave in these cases? Advice is accepted.

**Comment by Kilian** [comment]
see here: https://github.com/Kilian/fromscratch#faq
