### ISSUE TITLE
Add auto update or new version notificationd

### ISSUE THREAD

**Issue by spike1234** [Kilian/fromscratch#15]
Maybe it's already in there, but can you add an auto updater (maybe on program startup) or at least notify if there's a new version available?

Thanks!

**Comment by Kilian** [comment]
Long term.

For Ubuntu it would probably be nicer to offer a PPA. For all other systems, it's a long term plan. You'd either set up something like squirrel, or ping back to the server (over https) to get the latest version and test against current version. I'm not sure if I want it to ping back though.

**Comment by kwehner** [comment]
I'm not sure how to see which version I'm using. How about adding the version number to the FromScratch menu?

**Comment by spike1234** [comment]
or maybe in the title bar?

**Comment by Kilian** [comment]
I might switch this around, and add the version number to the menu, and a link to the releases page under "Check for updates", like how www.meetfranz.com/ does.

**Comment by Kilian** [comment]
This will be in FromScratch 1.1.0, and is now on master!

**Comment by Kilian** [comment]
Released in FromScratch 1.1.0
