### ISSUE TITLE
Multiple processes in Windows

### ISSUE THREAD

**Issue by ibipn** [Kilian/fromscratch#17]
I'm using v0.36.0 on Windows 7 64 bit machine. Whenever I launch the application, there are always two processes FromScratch.exe running (can be seen in Task Manager). Is this normal?

PS - Application is cool :)

**Comment by Kilian** [comment]
to be honest, I have no clue how electron works on windows 7 in that regard :)

**Comment by Kilian** [comment]
closing this for now as it's not a problem (and common in electron apps, it seems)
