### ISSUE TITLE
Copy & Paste

### ISSUE THREAD

**Issue by vagelim** [Kilian/fromscratch#2]
No copy and paste functionality severely limits the use of this app.

**Comment by Kilian** [comment]
Works fine for me. What OS are you using and from where to where are you copying?

**Comment by vagelim** [comment]
Thanks for the quick response! 

MacOSX El Capitan 10.11.3

Attempted to copy and paste from textedit to FromScratch, Sublime Text 2 to FromScratch, FromScratch to Chrome, Sublime and Textedit. None of the above tests worked. 

Note that I tried Cmd-C _and_ Ctrl-C for copy. Also tried to right-click to paste.

**Comment by Kilian** [comment]
Hmm. I rely on Codemirror to do the copying/pasting, I'm not sure how well it maps to OSX commands. On linux ctrl is ctrl, so it "just works". I'll look into it!

**Comment by Kilian** [comment]
In the meantime, you can get to your text by going to:

    ~/.fromscratch/content.txt

It's all there in plain text format, so nothing is lost :)

**Comment by lightsound** [comment]
I'm also in the same trouble.

MacOS Yosemite 10.10.5

**Comment by Kilian** [comment]
It's this lovely feature: https://github.com/atom/electron/issues/2308 one dummy menu coming up!

**Comment by Kilian** [comment]
There we go. You can download a fixed version here: https://github.com/Kilian/fromscratch/releases/download/v1.0.0/FromScratch-darwin-x64-1.0.1.zip

**Comment by vagelim** [comment]
:+1:

**Comment by lightsound** [comment]
Nice.
