### ISSUE TITLE
Shift+Tab doesn't outdent on Windows

### ISSUE THREAD

**Issue by notbalanced** [Kilian/fromscratch#20]
Hi, 
I'm running FromScratch on a number of Windows 7 boxes. It works great and is a nice notepad for taking notes in meetings.

The app does indenting perfectly, where the 2nd line after an indent will line up with the previous lines indent. However, when I go to outdent (shift-Tab), it doesn't do anything, and I have to backspace 4 times instead.

It would be great if you could add the Shift-Tab to outdent the current indentation level.

Thanks!

**Comment by Kilian** [comment]
I recently fixed this, it will be out in the next release I hope! https://github.com/Kilian/fromscratch/commit/bc96d3d9d6ef8de2ac352085c0714cacfe83671e
