### ISSUE TITLE
[FR]make menu in/visible with Alt-key only

### ISSUE THREAD

**Issue by thob** [Kilian/fromscratch#24]
in order to keep the interface clean and simple I'd prefer to have the menu only visible in rare moments. Hitting the alt key provides this (switching menu in/visible)  for instance in https://github.com/jiahaog/nativefier (another Electron project)

**Comment by Kilian** [comment]
Can you provide me with a screenshot of how the app looks for you with a menu? Alt to hide is a good addition.

**Comment by thob** [comment]
The menu items  – Edit, View, Window, Help – are at the same place I just toggle with Alt if I need them. Hope this helps. Funny thing is if I want to fire my screenshot tool (Linux Mint) the Alt triggered Mene is toggled to invisible ;-)

**Comment by Kilian** [comment]
just pushed the setting for this! I'll save up a few of these before making a new release but you can of course built your own! :)
