### ISSUE TITLE
Feature Request: Export to file

### ISSUE THREAD

**Issue by sguergachi** [Kilian/fromscratch#27]
Would be nice to be able to at the very least be able to export/dump the current stuff I wrote to a txt file so I can use later.

**Comment by Kilian** [comment]
Your content is saved on disk in a text file called content.txt already. On Mac and on Linux it's in ~/.fromscratch, and on windows it's in your users' AppData/.fromscratch folder. it's plain texts to you can back it up, symlink it to dropbox or do whatever! :) I'll add this to the readme too for clarity.

**Comment by sguergachi** [comment]
Thanks!
