### ISSUE TITLE
Allow changing of current doc

### ISSUE THREAD

**Issue by utahcon** [Kilian/fromscratch#28]
While I know the idea is a simplistic single pad for the thoughts... it would be nice to be able to simply change pages or note pads. Have one for work, and one for home. Looking at your structure this seems to be easy enough by swapping out the file loaded/written to. I have forked and will attempt this if no one else gets to it sooner.

**Comment by Kilian** [comment]
To be honest, I have no interest in this but if you want to do it for yourself you're absolutely more than welcome and I'll definitely check it out :)

**Comment by Kilian** [comment]
closing this :)
