### ISSUE TITLE
[linux] Installation

### ISSUE THREAD

**Issue by NicoHood** [Kilian/fromscratch#3]
Is there a way to install the app properly into the right directories with desktop shortcut and such things?
It would also be nice if you can pack up a debian package if possible. That'd be super cool!

**Comment by IRus** [comment]
:+1: and even more. An ppa would be nice.

**Comment by Kilian** [comment]
If you use Ubuntu Unity and you "lock to launcher" it creates the appropriate .desktop files, i believe. You can then unlock it again and it should show up in your dash (it does for me anyway)

The electron-builder package could make a .deb file, but I haven't gotten it to work yet. Making a PPA is considerably more work (I've been there) so help would be appreciated :)

**Comment by circa1977** [comment]
What's the appropriate directory to drop the files into as an 'installation'?

**Comment by Kilian** [comment]
binaries usually go into /usr/bin/ but I have to admit that I don't know how it works for electron apps, given that they have additional files.

**Comment by circa1977** [comment]
There are a handful of apps on here installed in `/opt` (`google/chrome`, `HipChat`, `rocketchat`, `vivaldi-beta`), which seems appropriate as precedent to follow.

**Comment by Kilian** [comment]
That sounds like a smart idea, as atom does that too. I hope electron-builder does that automatically

**Comment by circa1977** [comment]
Note that I use Atom, too, and do not see it in that same location.

**Comment by IRus** [comment]
`/opt/fromscratch` - looks like good idea

**Comment by NicoHood** [comment]
I use elementary os and i cannot doc the app just like that. I need to manually create a desktop file in the right directory. As mentioned an installation/ppa would be highly appreciated.

**Comment by IRus** [comment]
https://github.com/jordansissel/fpm
I found that this project used for creating deb packages, but there are ruby, and i don't like to install it on my system. What about an docker container?

**Comment by Kilian** [comment]
I would prefer a solution using https://github.com/loopline-systems/electron-builder as that can go into the existing build scripts.

**Comment by silentboatman** [comment]
I made a package for Arch :)
https://aur.archlinux.org/packages/fromscratch-bin/

**Comment by Kilian** [comment]
@silentboatman cool! what would be the appropriate way to communicate this on the site & on https://github.com/Kilian/fromscratch/releases ?

**Comment by silentboatman** [comment]
It should be enough to mention that it's in the AUR. And maybe linking to the AUR webpage. Something like this https://github.com/visit1985/mdp

**Comment by Kilian** [comment]
Thanks, have added it to the release and the readme!

**Comment by mec337** [comment]
Hello,
I am having library issues trying to use chromebook running trusty. dpkg -S implies I have the correct libraries available. Has anyone else tried this? was looking for cross platform support and this seems perfect for my needs.

**Comment by Kilian** [comment]
@mec337 are you using the correct (64bit it seems) version?

**Comment by mec337** [comment]
@Kilian thanks for the heads up, uname -m revealed x86_64 not sure why I downloaded the 32bit version. :-)

I can confirm FromScratch on my ACER C720 chromebook running chrome os and trusty works as expected. Many thanks for the support and good luck with the project.

**Comment by Kilian** [comment]
The upcoming version 1.4.0 comes as a .deb, a .snap and an .appImage!
