### ISSUE TITLE
[suggestion] Backup of data file on startup

### ISSUE THREAD

**Issue by beppe9000** [Kilian/fromscratch#31]
You should make a backup of the data file on startup, in case of an abrupt termination or power interruption.

**Comment by Kilian** [comment]
Fromscratch reads in the file at launch and only updates the file after (each) keystroke. Have you had a problem where your data got lost?

**Comment by beppe9000** [comment]
Not with Fromscratch. Power outages are frequent in the countryside of my region, but I think the probability of a power outage in the exact same instant of a key stroke & note file update is very small indeed, so maybe it is not necessary to do this. We can close this issue for me.

**Comment by Kilian** [comment]
I'll close this then, as the chance of corruption is tiny. 

in any case, manually creating a backup of the file, or automatically writing it to git is always a possible (if nerdy) option!

**Comment by beppe9000** [comment]
Well, Dropbox will be.
