### ISSUE TITLE
[FR] allow sync via remotestorage.io

### ISSUE THREAD

**Issue by thob** [Kilian/fromscratch#32]
I'd like to sync across several PCs, [remotestorage](https://remotestorage.io/) would be a great addition

**Comment by Kilian** [comment]
The data is saved in ~/.fromscratch. Is is easy to configure remotestorage to "just" sync that folder?

**Comment by thob** [comment]
How would I configure remotestorage, there's no client afaik? I'm using the [5apps storage service](https://5apps.com/storage/beta)

**Comment by Kilian** [comment]
...I have no idea ;) If you have a syncing tool that easily syncs folders that is the way to go. I should probably write a page/wiki/help text with regards to this.

**Comment by thob** [comment]
OK remotestorage is just an API, I think each app has to integrate to support syncing

Am 21. September 2016 09:16:48 MESZ, schrieb Kilian Valkhof <notifications@github.com>:

**Comment by Kilian** [comment]
I don't want to add any singular syncing tool into Fromscratch (I'll be dependent on that or have to add a bunch of other option too). The contents of Fromscratch are just a textfile that you can easily copy over and backup (or automate that in a number of ways) and that is the "blessed" way of syncing.
