### ISSUE TITLE
Download link on your website is broken

### ISSUE THREAD

**Issue by buzkall** [Kilian/fromscratch#34]
Hello,
The app has suggested me to upgrade my version, but the link on the website it's broken

Website:
https://github.com/Kilian/fromscratch/releases/download/v1.2.0/FromScratch-darwin-x64-1.2.0.zip
The one that works:
https://github.com/Kilian/fromscratch/releases/download/1.2.0/FromScratch-darwin-x64-1.2.0.zip

**Comment by Kilian** [comment]
oops! those links now work again :) thanks!
