### ISSUE TITLE
Windows app

### ISSUE THREAD

**Issue by codesharkasm** [Kilian/fromscratch#35]
For windows, make `frame:false` in the `browserWindow` in `main.js`. Optionally include window controls within the app window, or just use keyboard shortcuts. Make window always on top, and reduced opacity when not in focus. Because there is no frame, you may want to assign an element a `draggable` property. Love FromScratch, keep up the good work!

**Comment by Kilian** [comment]
I want to use native window controls, and windows currently does not have a native window-controls-inside-app option the same as mac does. This is why only mac gets the no-frame option, but both windows and linux have a frame. Perhaps I could color the frame like my background and make it less noticable, I'll look into that!
 
You should use other tools to pin to top and make transparent (I have both natively in my window manager on ubuntu, which is where that type of functionality is best applied.)
