### ISSUE TITLE
Shortcut helper..

### ISSUE THREAD

**Issue by rucuriousyet** [Kilian/fromscratch#37]
Hi, I love this tool but I am really hoping for one feature in specific. I can't really remember the shortcut commands, It would be really awesome if a helper could be made just like the "Already saved" dialog/message that when CMD or CTRL is pressed would show with a small list of the shortcuts combos.
For example ```+ | - zoom in/out```. I would be willing to help implement this. The other feature I would like to request would be a way of changing between files or notepads of some sort. At the very least it would be nice to be able to "bookmark" a vertical position in the text as a separate note that could later be used to navigate between notes or see a list of notes.

Thanks!

**Comment by Kilian** [comment]
Closing this in favor of #25. Would either having the shortcuts listed initially, or an overlay with shortcuts upon pressing F1 be an option?

your second feature can be done by using search (ctrl + f) or go to line (ctrl + g) Just do "=Work" and "=Personal" above a section and you can easily ctrl+f to it :)
