### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by bighi** [Kilian/fromscratch#38]
Download links on fromscratch.rocks are not working. They all just give a 404 error.

It's probably because they link to a releases folder in this repo, and there's no such folder.

**Comment by Kilian** [comment]
Releases are available here: https://github.com/Kilian/fromscratch/releases/tag/v1.2.0 I'll check why the links no longer work. Thanks for bringing this to my attention!

**Comment by Kilian** [comment]
Fixed the links. Thanks again for bringing this to my attention :)
