### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by nkantar** [Kilian/fromscratch#39]
I've found it helpful when projects keep a changelog and have taken to following the [Keep a Changelog](http://keepachangelog.com/) approach myself. Even if it rarely gets used, it makes following changes through versions easy when needed.

If this seems desirable, I'd be happy to submit a PR with the file skeleton and whatever information is available on the [Releases](https://github.com/Kilian/fromscratch/releases) page.

**Comment by Kilian** [comment]
I keep my changelog on the https://github.com/Kilian/fromscratch/releases page, with each proper release receiving a changelog. I'm not interested in doubling my work by also keeping it elsewhere, sorry.

**Comment by nkantar** [comment]
No worries—thanks for responding!
