### ISSUE TITLE
[Feature request] Supporting multiple contexts

### ISSUE THREAD

**Issue by NicoHood** [Kilian/fromscratch#4]
I know that you want to keep the app simple and that is great. However having different tabs would be extremely cool. Then you can do different TODO list without a lot of scrolling.

To get an idea of a possible look, here is a screenshot from the scratch text editor on elementary os:
![screenshot from 2016-02-11 20 27 57](https://cloud.githubusercontent.com/assets/6888294/12987787/006b392c-d0fe-11e5-9f8f-cdfd14cb8a20.png)

**Comment by Kilian** [comment]
I definitely want to support multiple contexts for note taking, of which tabs is one way, but maybe there are other solutions too. I'm still thinking of the best way to do this. 

Possible solutions:

* tabs
* multiple columns
* "code" folding
* multiple windows

In terms of tabs or something like scrollable columns I think both could work and look nice. What I want to preserve is that there is an actual file-on-disk that FromScratch uses (and that you can symlink, backup, version control), and what I don't want to add it explicitly named contexts, as I feel this is too much complexity. 

Additionally, if we autosave everything, you "close" a tab and then reopen the tab, what do you expect? Should we have deleted content (that goes counter to autosaving) or should we show the content that was in that tab (that might catch people off guard). 

That's my thinking on multiple contexts as-of-now, but any input is welcome :)

**Comment by NicoHood** [comment]
I like tabs the most.

Multiple windows are bad if you reopen/close the program.
Code folding just makes the scrolling more complicated but doesnt solve the issue.
Multiple columns can be useful, but tabs might just suit better.

If you close a tab it should delete all data. Just to erase it. Thats what i expect from an application. Adding a warning isnt bad though.

For the naming of the tabs I'd just use the first line of the tab as headline. That makes it less complicated.

**Comment by JohnSandel** [comment]
+1 for tabs, pls.

**Comment by macosxguru** [comment]
The lure of **FromScratch** is that it is small and simple. It is not trying to be a text editor replacement. It is ideal at just handling one page of text. That page can be as large as you want it to be, but it is one page. Introducing tabs seems to be an attempt to make it a text editor. Multiple windows will have the same effect. Now you have different windows to cycle through to get anything done.

I like the idea of a single window. I would encourage code folding to be a part of the application. That would make it easier to have different elements in the same window. But tabs? I am not so sure.

**Comment by adiultra** [comment]
Tabs are great, but then would come the problem of handling them, I would really like that I could save the text in tabs to a external human readable or plain text file which then could be loaded in any other FromScratch Instance.

**Comment by Kilian** [comment]
I am leaning towards code-folding for now, for reasons @macosxguru mentioned.

@adiultra I do not plan on adding the ability to open files in fromscratch.

**Comment by spike1234** [comment]
tabs +1

**Comment by adiultra** [comment]
umm How about a sidebar, no opening or closing for tabs, click the note to view, edit etc. And no multiple open notes. Simple and straightforward. Just like sidebar in atom or sublime. 

_The sidebar should give all the notes of the app rather than the opened ones_

Check [this](http://www.get-notes.com/) for inspiration.

**Comment by drsparks68** [comment]
I'd be perfectly happy with a sidebar (vertical tabs) or the usual horizontal ones.  I feel that multiple windows might get messy for folks like myself who store anywhere from 20 to 30 notes.  I have to respectfully disagree with @macosxguru; I think that it can have a tabbed interface and still be small and simple.  I'm thinking along the lines of a cleaner, sharper way to implement those horrible sticky notes for Windows...just in tabs rather than random windows on my desktop.

**Comment by ssylvia** [comment]
+1 for tabs or sidebar

**Comment by adouglas** [comment]
+1 for folding.

I also like the idea of a side bar or map of some kind. In keeping with the spirit of having just one "page" be it as long as you want, some sort of automated mapping/navigation would be nice.

Either an auto-hide mini map which highlights folds (or allow us to select text and turn it into large ascii art text which can be read in the mini-map). 

Or allow text folding with headers, and an auto-generated index/nav pane so we could click to sections.

**Comment by bentsai** [comment]
I do not like tabs. It introduces complexity that goes against the vision of simplicity. What draws me to FromScratch is that it is a single page.

**Comment by hbons** [comment]
I would love to have multiple windows. Tabs are too complicated and not in the spirit of FromScratch.
Cmd+N would create a new window (these will have a slightly different background hue), and window positions are saved to optimise for spatial memory.

**Comment by Kilian** [comment]
@hbons would each window show the same document, just in different scroll positions?

**Comment by Kilian** [comment]
In the meantime I have been working on a version that has indent-based folding: 

![selection_017](https://cloud.githubusercontent.com/assets/41970/14288876/cf106624-fb58-11e5-8bee-18e3627f2f61.png)

You can hide/unhide by hovering before a line, where an collapse-icon will appear and you can click it. Alternatively, you can press ctrl+alt+[ or ctrl+alt+] to toggle folding. It does not save your folded areas between restarts yet, which is something that should be added before it's in a proper release.

What is important to me is that, if you do not choose to use folding, it should never get in your way and by default the UI should remain as simple as in version 1.0.0.

It's available in the foldable-editor branch for people that want to try it out, I'm keen on feedback.

**Comment by thob** [comment]
I think simplicity rules. So rather resist the tempation of complexity (tabs etc) by introducing another editor. That's why I favor **folding**.
Even this adds already complexity to the notion of one page note-taking

**Comment by Kilian** [comment]
The foldable-editor branch now contains a version that remembers your folded areas between restarts. This will probably be added in version 1.1.0.

**Comment by Kilian** [comment]
Folding is now in the master branch. I've been using it for the past two weeks and I'm confident this is the best way to offer support for switching contexts without adding complexity. This will be added to FromScratch 1.1.0

**Comment by Kilian** [comment]
Released in FromScratch 1.1.0
