### ISSUE TITLE
Cmd+A closes the window instead of normal behaviour

### ISSUE THREAD

**Issue by thomasgrnr** [Kilian/fromscratch#40]
Pretty cool project man :)

I tried doing a quick and instinctive Cmd+A and backspace on MacOS to quickly clean the scratch and it closed the app. Unexpected behavior !

You think that could be corrected ?

Greetings from Paris ^^

**Comment by Kilian** [comment]
You're using an Azerty keyboard[1]. There are problems with alternative keyboard layouts in Electron, the system FromScratch uses, please see https://github.com/Kilian/fromscratch/issues/9 I assume you're using electron 1.2.0 (latest version)?

I'm closing this in favor of keeping #9.

[1] my awesome deduction powers combined "greetings from Paris" and "ctrl+A closes FromScratch"
