### ISSUE TITLE
checkboxes don't work on German keyboard layout

### ISSUE THREAD

**Issue by thob** [Kilian/fromscratch#42]
with German keyboard layout
OS: Linux Mint 17.3

v.1.3

**Comment by Kilian** [comment]
I've been able to replicate this. That's pretty unfortunate, it seems the / is under a shift key on a German keyboard, and on the place where on my keyboard a ~ is. Would it be ok to also add ctrl + ~ as a shortcut?

**Comment by thob** [comment]
~ is only accessible via Alt Gr + '+' in German
![German keys](http://www.keysourcechina.com/img/img/img/201171222472173499.jpg)

**Comment by Kilian** [comment]
any other suggestions?

**Comment by thob** [comment]
could you use `Alt Gr + [`

**Comment by fonorobert** [comment]
Chiming in to add that on Hungarian keyboard the characters `[ ] /` are all under either Shift or Alt as is `~` so folding and checkboxes don't work via the keyboard.

On a Hungarian keyboard only the following special characters are available without a modifier key: `, . -`

My recommendation would be to keep all shortcuts to letters, that would work across all languages.

ps. great little app btw, kudos!

**Comment by Kilian** [comment]
@fonorobert Thanks! with regards to the shortcut, a letter would work for all latin script indeed, but It would need to be one that doesn't interfere with other common shortcuts (it can't be ctrl+C, for example)

any objections to alt+b or ctrl+b ?

**Comment by fonorobert** [comment]
Ctrl+B might be confusing as it's the shortcut for bold text in most word processors. Alt+B would work although it might be better to keep it on Ctrl to be consistent with the other shortcuts already in the app. Maybe Ctrl+H would be an option? Then fold/unfold could be Ctrl+J and Ctrl+K, this way most shortcuts would be on the home row for touch typists :)

**Comment by Kilian** [comment]
I want to keep the ctrl+[ and ctrl + / shortcuts too, so I need to pick some that are not likely to become better suited for later functionality (when it comes up)

* Ctrl+L for checkbox 
* Ctrl+K for fold/unfold?

**Comment by fonorobert** [comment]
That sounds reasonable :)

**Comment by thob** [comment]
still no checkboxes for German?

**Comment by Kilian** [comment]
Thanks for the reminder, completely overlooked this. I have added the aforementioned Ctrl+L and Ctrl+K shortcuts, they will be in 1.4.1

**Comment by Kilian** [comment]
released here: https://github.com/Kilian/fromscratch/releases/tag/v1.4.1

**Comment by thob** [comment]
👍


1. Aug. 2018, 00:24 von notifications@github.com:
