### ISSUE TITLE
Misleading intro

### ISSUE THREAD

**Issue by sergeevabc** [Kilian/fromscratch#43]
Kilian, you must be crazy calling this app little as its Winx64 version requires 141 MiB of space.
Evaluate [Writemonkey][1] for comparison at least, which brings similar and other features for 28 MiB.
 
[1]: http://writemonkey.com/

**Comment by Kilian** [comment]
Honestly, what do you want to accomplish with this? If you prefer Writemonkey, use Writemonkey.

**Comment by sergeevabc** [comment]
It’s not about choice, some things like junk food eateries should be bashed by default.
This piece of software is a huge example of irresponsible polluting practice.
Think twice and cut once, says the proverb, while contributing to the world.
