### ISSUE TITLE
"⌘ + A" and "⌘ + Z" quit on French keyboard

### ISSUE THREAD

**Issue by lionep** [Kilian/fromscratch#45]
On AZERTY keyboards, it seems that shortcuts use the QWERTY layout, and 
`⌘ + A` acts like `⌘ + Q`
`⌘ + Z` acts like `⌘ + W`

I think it might happen on other keyboard layouts, with other shortcuts.

**Comment by Kilian** [comment]
Are you using the latest version of FromScratch?
