### ISSUE TITLE
Can you please make fromscratch available for fedora via package manager?

### ISSUE THREAD

**Issue by vasanthaganeshk** [Kilian/fromscratch#47]

**Comment by Kilian** [comment]
Someone did this for Arch linux. If anyone wants to make/host an RPM I'd be more than happy to link to it.

**Comment by Kilian** [comment]
Would a .snap or an .appImage also work? Those will be available with v1.4.0, released in the coming week.

**Comment by Kilian** [comment]
You can install Fromscratch via snapcraft or get the appimage here: https://github.com/Kilian/fromscratch/releases/tag/v1.4.1 does that work for you?

**Comment by Kilian** [comment]
closing this for now. Feel free to re-open.
