### ISSUE TITLE
Problem with running FromScratch on Windows 10 x64

### ISSUE THREAD

**Issue by audiowaves** [Kilian/fromscratch#48]
Hello. I have a problem with running FromScratch in Windows 10 x64. Previously it was ok, but after using CCleaner app can't start. After downloading latest version of FromScratch again and replacing all files in the folder error still exists.

It would be great to catch such errors and gently restore app to the working state if it is possible.

![11](https://cloud.githubusercontent.com/assets/2100323/22512440/b33ad4d4-e8a1-11e6-9937-ed176a5a18bd.PNG)

**Comment by Kilian** [comment]
This doesn't seem like an error I can gently recover from. Apps like CCleaner can do a lot of damage by deleting files in this way. 

I think your fromscratch appData is corrupt. Please go to your appData folder, (http://www.pcworld.com/article/2690709/windows/whats-in-the-hidden-windows-appdata-folder-and-how-to-find-it-if-you-need-it.html ) and rename the fromscratch folder to make a backup, and try restarting the application again. This doesn't delete the content in your fromscratch, as that resides in a different folder.

**Comment by olehch** [comment]
Sorry, but this solution didn't work for me.

note: after launch folder **FromScratch** is restored, but it is empty

**Comment by Kilian** [comment]
I can't help out any more here, I don't have enough windows knowledge.

**Comment by Jamezhall** [comment]
Not sure if this is similar but I just got this error on Windows 10 64 bit after trying to move the window. First time this has happened and I use this app daily.
I restarted the app, & in my case the data was still there.
Hope this helps somehow.

![rtscreenshot - 2018-05-11 10 46 - 01](https://user-images.githubusercontent.com/19564725/39901115-cf7678f8-5509-11e8-9ffe-9b36050e3329.png)

**Comment by Kilian** [comment]
Closing this ticket. If it's still an issue even with 1.4.2, please feel free to re-open!
