### ISSUE TITLE
Add Alt menu toggle to shortcut list

### ISSUE THREAD

**Issue by alexenglish** [Kilian/fromscratch#55]
I was about to post an issue about not being able to figure out what version number I was running, so as to tell if I was up to date. After looking around in other tickets I found that the menu can be toggled by pressing Alt. It would be helpful to have this documented more visible. Maybe I just missed it.

Cheers!

**Comment by Kilian** [comment]
You're right. I work on Ubuntu and macOS, both of which have a global menu and alt does nothing, so it simply didn't occur to me. i'll add it to the site and to the readme!

**Comment by Kilian** [comment]
done! :)
