### ISSUE TITLE
Running v 1.3.0 and Ctrl+i does not change theme

### ISSUE THREAD

**Issue by Jamezhall** [Kilian/fromscratch#60]
Hi, I'm running v 1.3.0 and Ctrl+i does not change the colour theme. Running the windows version. 

![image](https://user-images.githubusercontent.com/19564725/35654749-8fce9d58-0742-11e8-9bb6-6d8358a3d17e.png)

Is there another version somewhere or an update?

**Comment by Kilian** [comment]
Hi! The light colour mode isnt released yet! I want to get a few more feature in before releasing a new version :)
