### ISSUE TITLE
Multi monitor remember position

### ISSUE THREAD

**Issue by eboye** [Kilian/fromscratch#61]
First of all, I'm in love with the app, I would not change a bit in it :) it's like having a peace of paper by my side.

The only thing I'm having trouble with is that I made it start with system, but this way it always goes on primary monitor where I need to move it every single time to the second monitor.

Is there a way FromScratch can remember which monitor it was on? Almost all other apps do that.

Thanks

**Comment by Kilian** [comment]
FromScratch does that for me on linux without any issues. Which OS are you using, which multimonitor configuration are you using (I suppose you extend your desktop?), and are you launching fromscratch before or after you plug in your second monitor/before or after your operating system shows anything on your second monitor?

**Comment by eboye** [comment]
@Kilian yes, it was ... now it seems to be working after few beta updates. Am currently on 1.4.1

**Comment by Kilian** [comment]
awesome, then I'll close this ticket :)
