### ISSUE TITLE
Shortcut for Cut and Copy is the same

### ISSUE THREAD

**Issue by nilicule** [Kilian/fromscratch#64]
It seems the shortcut for Cut and Copy is the same (CMD C). This can lead to some unexpected results when selecting all text in the scratchpad and hitting 'copy'.

**Comment by Kilian** [comment]
Shit, that looks like a ...copy and paste error. :sunglasses: Mac only, luckily

fix incoming :(

**Comment by Kilian** [comment]
^ that fixes it, I'll get 1.4.1's up shortly.

**Comment by Kilian** [comment]
Prerelease available here: https://github.com/Kilian/fromscratch/releases/tag/v1.4.1

Will close this ticket when it's released properly, hopefully with fixes for #65.

**Comment by Kilian** [comment]
available here: https://github.com/Kilian/fromscratch/releases/tag/v1.4.1
