### ISSUE TITLE
Feature request: Find/Search

### ISSUE THREAD

**Issue by kristianwithak** [Kilian/fromscratch#7]
Hey there! Thanks for this app, it beats my habit of opening TextEdit and ending up with dozens of files on my desktop by far.

That said, one feature that would totally rock serious ass for me is some sort of "Find" feature.

I can imagine the possibly-infinitely-long-page being tough to sift through, but a simple `control+F` to find a word you remembered typing would be dope.

Thanks! :-D

**Comment by Kilian** [comment]
I like it, though I'm not sure if I want to focus on it straight away, so it could be a couple of (minor) releases away.

**Comment by kristianwithak** [comment]
Awesome, makes perfect sense... looking forward to that feature coming through, and thanks again for the great work. :-D

**Comment by rdjs-is** [comment]
I'd just like to second this request for exactly the same reasons as above. I would really favour keeping everything very simple, as a train of thought application (without themes, tabs etc.) but search would make the resulting bit of text much more useful in the long run.

**Comment by Kilian** [comment]
I'm working on this in the "searchable-text" branch, which now has:

* ctrl+f for search, 
* shift+ctrl+f for replace, 
* shift+ctrl+r for replace all, 
* alt+g for jump to line. 
* Esc to clear searching.

It highlights the match in the text as well as in the scrollbar, here's a screenshot:

![selection_003](https://cloud.githubusercontent.com/assets/41970/18815954/f0c70458-833e-11e6-8820-faf4e5bdf937.png)

I'll be testing this out for my self for the coming days, and merge it back in soon. You can try it for yourself by using the searchable-text branch and building fromscratch yourself.

**Comment by Kilian** [comment]
This is now in version 1.2.0, up for download, and an update message will appear tomorrow! https://github.com/Kilian/fromscratch/releases/tag/1.2.0

**Comment by kristianwithak** [comment]
Awesome! So glad this got in... thank you! :-D
