### ISSUE TITLE
Unable to click on, or move the cursor to, the last line of softwrapped text

### ISSUE THREAD

**Issue by AndrewWhiteat70ms** [Kilian/fromscratch#70]
Paste in enough copy that you have more than three lines of softwrapped text. If you attempt to click on the last line, you will not be able to. Cursor to the line above the last line. Attempt to move down, and you will skip down to the line below your text. Cursor up, and you will skip one line up, and go to the second last line.

This does not occur if the softwrapped line is at the end of a document.

Using MacOS 10.13.6 (17G65). FromScratch 1.4.1.

**Comment by Kilian** [comment]
this link should work: this should work: https://github.com/Kilian/fromscratch/releases/download/v1.4.2-beta/FromScratch-1.4.2.dmg @AndrewWhiteat70ms

**Comment by Kilian** [comment]
released: https://github.com/Kilian/fromscratch/releases/tag/v1.4.2
