### ISSUE TITLE
Titlebar on high sierra is transparent

### ISSUE THREAD

**Issue by Kilian** [Kilian/fromscratch#72]
mentioned by @husainfazel and seen elsewhere too, this is a electron bug supposedly fixed in 2.0: https://github.com/electron/electron/pull/11886

<img src="https://user-images.githubusercontent.com/418404/43489043-f11ac73c-951b-11e8-8f71-b88e1dd40c2e.png">

**Comment by husainfazel** [comment]
I think the link above is incorrect?

**Comment by Kilian** [comment]
this should work: https://github.com/Kilian/fromscratch/releases/download/v1.4.2-beta/FromScratch-1.4.2.dmg

**Comment by husainfazel** [comment]
Just wanted to confirm that 1.4.2 fixes the title bar issue.
![screen shot 2018-09-10 at 14 47 38](https://user-images.githubusercontent.com/418404/45298327-790c1180-b508-11e8-832c-cf5d7475bdba.png)

**Comment by Kilian** [comment]
released in https://github.com/Kilian/fromscratch/releases/tag/v1.4.2 If you have the above version, it's identical.
