### ISSUE TITLE
Dark Theme is unusable on OSX Mojave

### ISSUE THREAD

**Issue by beaudesigns** [Kilian/fromscratch#75]
Hey Kilian! Just letting you know that on the dark theme on OSX Mojave, text isn't readable except for the highlighted line. Screenshots attached.

![screen shot 2018-09-28 at 8 02 08 am](https://user-images.githubusercontent.com/193887/46209957-ec799580-c2f4-11e8-9456-10bb4308a3d3.png)
![screen shot 2018-09-28 at 8 02 12 am](https://user-images.githubusercontent.com/193887/46209958-ec799580-c2f4-11e8-8e77-df444269e7a7.png)

It can be worked around by using the light theme for now!

**Comment by Kilian** [comment]
Macos has so many issues :( Are you running the mojave dark theme too, or the mojave light theme?

**Comment by beaudesigns** [comment]
Haha, us Mac users have many needs. :) I'm using the Mojave light theme.

**Comment by smstarr** [comment]
Kilian, I use Mojave Dark Theme and can confirm that it is doing the same thing.  I am currently using the bandage of the light theme in FromScratch as a work around.

**Comment by Kilian** [comment]
I finally upgraded to mojave so can now see this as well, I'll work on a fix shortly!

**Comment by Kilian** [comment]
This version should fix it (it does for me), can anyone verify? https://github.com/Kilian/fromscratch/releases/download/untagged-1202b55297ca612e5903/FromScratch-1.4.3.dmg

**Comment by beaudesigns** [comment]
I'm game to test. I get a 404 on that download though.

**Comment by Kilian** [comment]
Updated link: https://github.com/Kilian/fromscratch/releases/download/v1.4.3-beta/FromScratch-1.4.3.dmg

**Comment by beaudesigns** [comment]
@Kilian I've tested. Can confirm: fixes text color on the dark theme.

You rock!

**Comment by Kilian** [comment]
Great to hear, i'll get the proper release out tomorrow!

**Comment by Kilian** [comment]
solved in 1.4.3!

**Comment by StefanRudvin** [comment]
This may be due to new OSX updates, but I am getting the same issue :(

**Comment by Kilian** [comment]
@StefanRudvin using 1.4.3 on mojave?

**Comment by StefanRudvin** [comment]
Yes, 1.4.3 on mojave 10.14.5 with a 2013 Macbook pro retina.
