### ISSUE TITLE
indented word wrap

### ISSUE THREAD

**Issue by kitzopo** [Kilian/fromscratch#8]
It would be great if the automatic indenting would also wrap lines accordingly:

![screenshot_173](https://cloud.githubusercontent.com/assets/2832670/13043756/58d645d8-d3ca-11e5-89c1-163bb7d3b191.png)

Thanks,
Kilian

**Comment by Kilian** [comment]
Seems we can do that with a hack: https://codemirror.net/demo/indentwrap.html I'll look into it.

**Comment by kitzopo** [comment]
Great…

**Comment by Kilian** [comment]
Very hard to get working in a consistent and logical way. I'll look at it one more time but otherwise I think I'm gonna leave this. as either wrapping the line to the next line or indenting is both feel o.k. to me.

**Comment by Kilian** [comment]
I can't get this to work in a natural way, so closing this for now and keeping it the way it is: long lines wrap. If anyone makes a nice pull-request that does work in nicely expected ways i'll accept it.
