### ISSUE TITLE
Remove "Welcome" text after first use

### ISSUE THREAD

**Issue by bryantpeng** [Kilian/fromscratch#81]
Hi Kilian! I absolutely love FromScratch, it's something I use every day on both personal and work computers. So simple but so effective.

My only request is that the "Welcome to FromScratch" text be removed after your first use. I clear my notepad from time to time, and if you quit while the notepad is clear then it'll reappear the next time you launch. Then you have to Cmd-A and delete it, which is minor but still an inconvenience—it's not like you need the tutorial again.

Thanks for continuing to support this app!

**Comment by Kilian** [comment]
Ah, yes. I try to load in content and that resolves to an empty string if there is no initial file, and I use that as a trigger to determine if I should show the welcome message. I can see how that is a problem if you delete everything, Let me see what I can do!

**Comment by Kilian** [comment]
Fixed in the next version! :)

**Comment by bryantpeng** [comment]
Ahhh thanks so much!!
