### ISSUE TITLE
Toggle Fullscreen

### ISSUE THREAD

**Issue by eLefTrick6** [Kilian/fromscratch#82]
After Toggle Fullscreen, the window successfully resizes to fullscreen, however when attempting to Toggle Fullscreen back to normal will not restore. Attempting to click the titlebar's Restore is disabled (since the dialog is acting as resized normal not as maximized). Can click to maximize window, no action, click to restore dialog, no action. Attempt to resize the dialog by the resize grab bars on window borders and corners fail to allow resize (maybe because the dialog still thinks it is in fullscreen mode?). from the application's System Menu or right-click on the titlebar, select Size then use arrow keys and mouse to resize the dialog box, it will allow this, then Enter, and the size will keep. However the dialog box still does not allow normal resizing behavior, or pressing F11 to Fullscreen or Alt to access the application's menu Togle Fullscreen, still do not toggle back from fullscreen to a normal window behavior. 
Running 1.4.3, happens on several Win 10 machines.

**Comment by eLefTrick6** [comment]
Note this issue is related to and duplicates https://github.com/Kilian/fromscratch/issues/74 unable to resize

**Comment by Kilian** [comment]
I don't have access to a windows machine at the moment, but when I do I'll look at both issues. Thanks for bringing it to my attention!

**Comment by Kilian** [comment]
i do and can confirm this. I'll look into it!

**Comment by Kilian** [comment]
will get this in the next release!
