### ISSUE TITLE
Folding note keybindings don't seem to work

### ISSUE THREAD

**Issue by thejohnha** [Kilian/fromscratch#85]
I'm trying to use CMD-[ and CMD-] on macOS. But instead of folding and unfolding, it increases/decreases the font size.

Just curious if this is an error... or if something else is going on.

If may be because I'm using the dvorak keyboard layout. In which case this is a duplicate of Issue #77 and I apologize.

Thank you so much,
John

**Comment by Kilian** [comment]
Yeah it's issue #77, the shortcuts all map to qwerty keyboards. I don't have a ton of time to fix this but I hope Electon will solve it soon.

**Comment by thejohnha** [comment]
Ah thanks man. Closing this now in lieu of #77 - I'll stay tuned to see if there's any developments there. Just installed today and loving it so far. Thank you!!!
