### ISSUE TITLE
Fullscreen toggle on windows doesn't seem to work

### ISSUE THREAD

**Issue by SivertGullbergHansen** [Kilian/fromscratch#87]
When I press f11 it toggles the fullscreen. The window is resized to the resolution of my desktop/monitor, but when I press it again to **toggle** fullscreen, nothing happens. :)

I am using the latest build available as of 06 Feb. 2020

**Comment by idelem** [comment]
Same here, on Win 10 and latest build as of 12 Mar, 2020

**Comment by khevmoore** [comment]
If you want to fix this manually, search for the windowstate file and revert back to the default settings.

{"isMaximized":false,"bounds":{"x":-1029,"y":532,"width":550,"height":450}}

**Comment by lampo808** [comment]
Same here just discovered.
